name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build wheels
        uses: joerick/cibuildwheel@v2.1.2
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_TEST_COMMAND: "python -m pymunk.tests"
          CIBW_BUILD_VERBOSITY: 3
      - uses: actions/upload-artifact@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          path: ./wheelhouse/*.whl
          retention-days: 7
